version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.25
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/fluentd/log
    ports:
      - "24224:24224"

  kibana:
    image: kibana:7.17.25
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

  node_app:
    build:
      context: ./node_app
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
    ports:
      - "3000:3000"
    depends_on:
      - fluentd
    restart: always

volumes:
  elastic:
